(define generate-c-assembler (lambda (filename) (call-with-new-output-file filename c-write-assembler)))

(define c-write-assembler (lambda (port) (say-to port "/* Generated by Miasma (http://github.com/darius/miasma) */") (say-to port) (call-with-input-file "c/asm_stuff.h" (lambda (in) (copy-port in port))) (say-to port) (say-to port (c-enum registers (map register-number registers))) (say-to port) (for-each (lambda (spec) (say-to port (c-gen (spec.mnemonic spec) (spec.params spec)))) the-specs)))

(define c-gen (lambda (mnemonic code-list) (let ((vars (c-make-variable-list (foldl + 0 (map c-variable-count code-list))))) (c-stmt-macro (c-insn-name mnemonic) vars (c-body (map c-parenthesize vars) code-list)))))

(define c-make-variable-list (lambda (n) (map (lambda (k) (string-append "v" (number->string k))) (iota n))))

(define c-body (lambda (vars code-list) (let walking ((code-list code-list) (stmts (quote ())) (vars vars)) (if (null? code-list) stmts ((walk-code (car code-list) c-code c-exp) vars (lambda (vars cv) (walking (cdr code-list) (cons cv stmts) vars)))))))

(define c-code (let ((flambda-1 (lambda (signed? count exp) (bind (lambda (cv) (unit (c-exp-stmt (c-call (string-append (if signed? "x86_push_i" "x86_push_u") (integer->string (* 8 count))) cv)))) exp))) (flambda-2 (lambda (code) (swapping code))) (flambda-3 (lambda (e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (c-exp-stmt (c-call "mod_rm" cv1 cv2)))) e2)) e1)))) (lambda (tag) (case tag ((bytes) flambda-1) ((swap-args) flambda-2) ((mod-r/m) flambda-3) (else (impossible (quote flambda) tag))))))

(define c-exp (let ((flambda-4 (lambda (n) (unit (c-int-literal n)))) (flambda-5 (lambda (operator e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (c-binop (symbol->string operator) cv1 cv2))) e2)) e1))) (flambda-6 (lambda () (unit "hereafter"))) (flambda-7 (lambda ignore (eating unit)))) (lambda (tag) (case tag ((literal) flambda-4) ((op) flambda-5) ((hereafter) flambda-6) ((arg) flambda-7) (else (impossible (quote flambda) tag))))))

(define c-variable-count (lambda (code) (define c-code (let ((flambda-8 (lambda (signed? count exp) exp)) (flambda-9 (lambda (code) code)) (flambda-10 (lambda (e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (+ cv1 cv2))) e2)) e1)))) (lambda (tag) (case tag ((bytes) flambda-8) ((swap-args) flambda-9) ((mod-r/m) flambda-10) (else (impossible (quote flambda) tag)))))) (define c-exp (let ((flambda-11 (lambda (n) (unit 0))) (flambda-12 (lambda (operator e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (+ cv1 cv2))) e2)) e1))) (flambda-13 (lambda () (unit 0))) (flambda-14 (lambda ignore (unit 1)))) (lambda (tag) (case tag ((literal) flambda-11) ((op) flambda-12) ((hereafter) flambda-13) ((arg) flambda-14) (else (impossible (quote flambda) tag)))))) ((walk-code code c-code c-exp) (quote _) (lambda (_ count) count))))

(define c-enum (lambda (symbols values) (string-join (quasiquote ("enum {" (unquote-splicing (map (lambda (sym val) (string-append "  " (as-legal-c-identifier (symbol->string sym)) " = " (c-int-literal val) ",")) symbols values)) "};")) (string #\newline))))

(define c-int-literal (lambda (n) (if (and (<= 0 n) (exact? n)) (string-append "0x" (number->string n 16)) (integer->string n))))

(define c-binop (lambda (operator cv1 cv2) (string-append "(" cv1 " " operator " " cv2 ")")))

(define c-parenthesize (lambda (cv) (string-append "(" cv ")")))

(define c-call (lambda (fn-cv . args-cv) (string-append fn-cv " (" (string-join args-cv ", ") ")")))

(define c-exp-stmt (lambda (cv) (string-append cv ";")))

(define c-stmt-macro (lambda (name vars stmts) (string-join (quasiquote ((unquote (c-declare name vars)) "  do {" "    const u8 *hereafter = x86_bptr;" (unquote-splicing (map (lambda (stmt) (string-append "    " stmt)) stmts)) "  } while (0)")) c-line-continuation)))

(define c-line-continuation (string #\space #\\ #\newline))

(define c-declare (lambda (name vars) (string-append "#define " name "(" (string-join vars ", ") ")")))

(define c-insn-name (lambda (mnemonic) (as-legal-c-identifier (string-append "x86_" (symbol->string mnemonic)))))

(define as-legal-c-identifier (lambda (str) (list->string (map (lambda (c) (case c ((#\- #\.) #\_) ((#\?) #\c) (else c))) (filter (lambda (c) (not (memq c (quote (#\: #\%))))) (string->list str))))))

