(define generate-py-assembler (lambda (filename) (call-with-new-output-file filename py-write-assembler)))

(define py-write-assembler (lambda (port) (say-to port "# Generated by Miasma (http://github.com/darius/miasma)") (say-to port) (call-with-input-file "python/x86_stub.py" (lambda (in) (copy-port in port))) (say-to port) (say-to port (py-enum registers (map register-number registers))) (say-to port) (for-each (lambda (spec) (say-to port (py-gen (spec.mnemonic spec) (spec.params spec)))) the-specs)))

(define py-gen (lambda (mnemonic code-list) (let ((vars (py-make-variable-list (foldl + 0 (map py-variable-count code-list))))) (py-stmt-macro (py-insn-name mnemonic) vars (py-body vars code-list)))))

(define py-make-variable-list (lambda (n) (map (lambda (k) (string-append "v" (number->string k))) (iota n))))

(define py-body (lambda (vars code-list) (let walking ((code-list code-list) (stmts (quote ())) (vars vars)) (if (null? code-list) stmts ((walk-code (car code-list) py-code py-exp) vars (lambda (vars cv) (walking (cdr code-list) (cons cv stmts) vars)))))))

(define py-code (let ((flambda-15 (lambda (signed? count exp) (bind (lambda (cv) (unit (py-exp-stmt (py-call (string-append (if signed? "push_i" "push_u") (integer->string (* 8 count))) cv)))) exp))) (flambda-16 (lambda (code) (swapping code))) (flambda-17 (lambda (e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (py-exp-stmt (py-call "mod_rm" cv1 cv2)))) e2)) e1)))) (lambda (tag) (case tag ((bytes) flambda-15) ((swap-args) flambda-16) ((mod-r/m) flambda-17) (else (impossible (quote flambda) tag))))))

(define py-exp (let ((flambda-18 (lambda (n) (unit (py-int-literal n)))) (flambda-19 (lambda (operator e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (py-binop (symbol->string operator) cv1 cv2))) e2)) e1))) (flambda-20 (lambda () (unit "hereafter"))) (flambda-21 (lambda ignore (eating unit)))) (lambda (tag) (case tag ((literal) flambda-18) ((op) flambda-19) ((hereafter) flambda-20) ((arg) flambda-21) (else (impossible (quote flambda) tag))))))

(define py-variable-count (lambda (code) (define py-code (let ((flambda-22 (lambda (signed? count exp) exp)) (flambda-23 (lambda (code) code)) (flambda-24 (lambda (e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (+ cv1 cv2))) e2)) e1)))) (lambda (tag) (case tag ((bytes) flambda-22) ((swap-args) flambda-23) ((mod-r/m) flambda-24) (else (impossible (quote flambda) tag)))))) (define py-exp (let ((flambda-25 (lambda (n) (unit 0))) (flambda-26 (lambda (operator e1 e2) (bind (lambda (cv1) (bind (lambda (cv2) (unit (+ cv1 cv2))) e2)) e1))) (flambda-27 (lambda () (unit 0))) (flambda-28 (lambda ignore (unit 1)))) (lambda (tag) (case tag ((literal) flambda-25) ((op) flambda-26) ((hereafter) flambda-27) ((arg) flambda-28) (else (impossible (quote flambda) tag)))))) ((walk-code code py-code py-exp) (quote _) (lambda (_ count) count))))

(define py-enum (lambda (symbols values) (string-join (map (lambda (sym val) (string-append (as-legal-py-identifier (symbol->string sym)) " = " (py-int-literal val))) symbols values) (string #\newline))))

(define py-int-literal (lambda (n) (if (and (<= 0 n) (exact? n)) (string-append "0x" (number->string n 16)) (integer->string n))))

(define py-binop (lambda (operator cv1 cv2) (string-append "(" cv1 " " operator " " cv2 ")")))

(define py-parenthesize (lambda (cv) (string-append "(" cv ")")))

(define py-call (lambda (fn-cv . args-cv) (string-append fn-cv "(" (string-join args-cv ", ") ")")))

(define py-exp-stmt (lambda (cv) cv))

(define py-stmt-macro (lambda (name vars stmts) (string-join (quasiquote ((unquote (py-declare name vars)) "    global buf" "    hereafter = len(buf)" (unquote-splicing (map (lambda (stmt) (string-append "    " stmt)) stmts)))) (string #\newline))))

(define py-declare (lambda (name vars) (string-append "def " name "(" (string-join vars ", ") "):")))

(define py-insn-name (lambda (mnemonic) (as-legal-py-identifier (string-append "" (symbol->string mnemonic)))))

(define as-legal-py-identifier (lambda (str) (list->string (map (lambda (c) (case c ((#\- #\.) #\_) ((#\?) #\c) (else c))) (filter (lambda (c) (not (memq c (quote (#\: #\%))))) (string->list str))))))

